algoritmo "SomaParametrosReferencia"
// Função :
// Autor :
// Data : 17/06/2021
// Seção de Declarações 
var
    X, Y: inteiro
Procedimento Soma ( var A, B: inteiro)
inicio
      A <- A + 1
      B <- B + 2
      escreval(" Valor de A = ", A)
      escreval(" Valor de B = ", B)
      escreval(" Soma A + B = ", A+B)
FimProcedimento
inicio
      X <- 4
      Y <- 8
      Soma(X, Y)
      escreval(" Valor de X = ", X)
      escreval(" Valor de Y = ", Y)
fimalgoritmo
